### ISSUE TITLE
front: stdcm: times and durations (rounded?) leads to inconsistent display of stop times in summary

### ISSUE THREAD

**Issue by bougue-pe** [OpenRailAssociation/osrd#10660]
### What happened?

In STDCM, it's possible to obtain inconsistent time/duration values : arrival at stop is 9:13, departure from stop 9:19 and duration is 7 min.

### What did you expect to happen?

I expected the 3 values to be consistent.

Probably:
* on one hand decide if/how to round arrival/departure times (relates to https://github.com/OpenRailAssociation/osrd/issues/9179 too?):
  * precise to the second (no rounding)
  * closest
  * floor
  * ... ceiling looks weird IMO
* on the other hand compute stop duration to have a consistent display:
  * precise to the second (no rounding)
  * use the rounded arrival/departure time values for a duration rounded to the minute

We may as well assume to have inconsistent values (if all is rounded to the closest, it can happen), and maybe just precise exact values at hover?
Example (did not check exact values in provided case): arrival 9:12:35, departure 9:19:25 ⇾ duration 6:50

### How can we reproduce it (as minimally and precisely as possible)?

On STDCM, when playing the [test](https://github.com/osrd-project/osrd-tests/issues/76) by hand, at the step 24 an inconsistent display of times/durations was obtained, probably caused by rounding.

![Image](https://github.com/user-attachments/assets/f6cfffe7-556c-4667-a6c2-a48361911f53)

### On which environments the bug occurs?

Recette (SNCF), Production (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

v0.3.10 c9066aa

**Comment by Akctarus** [comment]
Should be fixed by : https://github.com/OpenRailAssociation/osrd/pull/10876, can't reproduce the bug since

**Comment by woshilapin** [comment]
Bug still observed on `dev` on the 26/03/2025.

![Image](https://github.com/user-attachments/assets/3cc0f4cd-ccf7-4093-a356-bb7bbf72e33c)

**Comment by bougue-pe** [comment]
As discussed a bit aside, here are the actions that we can engage (not sure what should be first):
1. determine the expected behavior (maybe we already have the expected behavior?)
2. mocking editoast's output that "creates" those cases and change values to make sure of the current behavior on:
  a. rounding arrivals
  b. rounding departures (probably the same as above)
  c. rounding stop durations (a quick look at the code suggests "round to the closest")
  -> We would then have "inconsistent" cases to work on
