### ISSUE TITLE
front: update a paced train into train schedule makes all upcoming operations fail

### ISSUE THREAD

**Issue by louisgreiner** [OpenRailAssociation/osrd#13410]
### What happened?

When switching from paced train to train schedule (or the inverse), the opened modal keeps targeting the previous timetable item state, then trying to update a deleted item instead of the new one

https://github.com/user-attachments/assets/863a25a8-f33e-4a6c-914d-688d1b11073d

scenario : https://dev-osrd.reseau.sncf.fr/operational-studies/projects/97/studies/452/scenarios/1331?selected_train=indexedoccurrence_739_0&projection=paced_739

### What did you expect to happen?

That the modal in NGE refers to the newly created timetable item

It might require some work on NGE side too, or do you see any other solution? @emersion @Synar 

### How can we reproduce it (as minimally and precisely as possible)?

1. create a train and open macro
2. change train schedule to paced train
3. keep updating fields on the same opened modal

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

(

**Comment by emersion** [comment]
I believe this has been fixed by https://github.com/OpenRailAssociation/osrd/pull/13583

**Comment by louisgreiner** [comment]
It is fixed indeed, really awesome 🥳

**Comment by louisgreiner** [comment]
Errors are still logged when switching back and forth from train schedule to paced train, might create a new issue

<img width="1919" height="911" alt="Image" src="https://github.com/user-attachments/assets/49282bf1-19e0-474b-a337-63c8cc62eb56" />

**Comment by emersion** [comment]
I've seen some of these 404s, it seems like simulation results logic (outside of the NGE-related code) doesn't cope well with deleted trains. Opening a new issue sounds good.

The 500s sound like they'd be an orthogonal issue, maybe trying clearing your Valkey cache?

**Comment by louisgreiner** [comment]
Thanks for the context. Created a [new issue to deal with 404s](https://github.com/OpenRailAssociation/osrd/issues/13841). As for the 500s, I tested on the sncf internal dev environment :/
