### ISSUE TITLE
STDCM: Starting a new query does not reset all the fields in the consist card

### ISSUE THREAD

**Issue by Maymanaf** [OpenRailAssociation/osrd#9533]
### What happened?

![Image](https://github.com/user-attachments/assets/d3b34009-bab8-4135-a58c-62d2b1ad58be)

### What did you expect to happen?

The fields should be emptied

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to stdcm, launch a request
2. Select the simulation
3. Click on reset the form

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

6d9ed21

**Comment by axrolld** [comment]
Sould be fixed by https://github.com/OpenRailAssociation/osrd/issues/9695

**Comment by celine-sncf** [comment]
Seems fixed for the "Convoi" card but still happening for the "Hour" field

**Comment by theocrsb** [comment]
I can't reproduce the bug

**Comment by sim51** [comment]
I reproduce it for the "hour field". 
In fact this field is also not changed when you switch from one simulation to an other.

I found a way to fix the "clean query" issue : in the component `StdcmOpSchedule` we pass to `TimePicker` the attribut `value` (as well as `hours` & `minutes` which are the good data).  By removing it, it works. 

But it doesn't fix my issue on simulation switch.

**Comment by theocrsb** [comment]
> I reproduce it for the "hour field". In fact this field is also not changed when you switch from one simulation to an other.
> 
> I found a way to fix the "clean query" issue : in the component `StdcmOpSchedule` we pass to `TimePicker` the attribut `value` (as well as `hours` & `minutes` which are the good data). By removing it, it works.
> 
> But it doesn't fix my issue on simulation switch.

The bug when switch from one simulation to an other should be [fix by this PR](https://github.com/OpenRailAssociation/osrd/pull/10192)

**Comment by sim51** [comment]
[PR](https://github.com/OpenRailAssociation/osrd/pull/10286) that fix the clear the hour field

**Comment by EthanPERRUZZA** [comment]
PR were merged, bug is fixed
