### ISSUE TITLE
When spamming the different result tabs, the "run the simulation" button reappears

### ISSUE THREAD

**Issue by Castavo** [OpenRailAssociation/osrd#9624]
### What happened?

https://github.com/user-attachments/assets/d32bf19b-c5b7-4c2d-b0a0-b34f81f10c8c

When spamming the different result tabs, randomly the "run the simulation" button reappears (usually takes a few tens of fast clicks between tabs)

### What did you expect to happen?

I expect the button to never reappear

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to https://dev-osrd.reseau.sncf.fr/stdcm
2. Make some simulations (I don't know how many you need exactly, at least two so you have tabs to switch between)
3. Quickly click on the different tabs
4. At some point the button should reappear

### On which environments the bug occurs?

Dev (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

pr 9602 (merge of fam/fix-user-identity@1e971f6 into dev@bfa5205)

**Comment by axrolld** [comment]
I'm guessing this is linked to [this bug](https://github.com/OpenRailAssociation/osrd/issues/9889). If the inputs don't change the form remains the same and the button never reappears.

Actually we might want to have the button always visible and clickable because it got some users very confused during the test. If they want to run he same simulation several times it's their loss imo. @thibautsailly what do you think ?

**Comment by thibautsailly** [comment]
It's our loss too, using computation capacity and server time for no benefit.
I think the confusion during the first half hour of usage is worth the lasting effect of having to be considerate when asking for a computation.
But I agree that the way it works now isn't ideal, and we can improve on it. We could display a message saying the form configuration is identical to a simulation below. And when we'll have requests history we'll need to adapt the message with the time elapsed since the simulation calculation.

**Comment by theocrsb** [comment]
Should be fixed by [this PR](https://github.com/OpenRailAssociation/osrd/pull/10192)

**Comment by Synar** [comment]
Since the aforementioned pr has been merged, can you still reproduce or can we close this? 

I personally couldn't reproduce, but I'm not a very fast clicker haha.

**Comment by Castavo** [comment]
I couldn't reproduce either
